config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :meals, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :weights, only: [:new, :index, :create, :edit, :update]

  get 'search' => 'search#search'
  get 'find' => 'search#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :meal_menus, dependent: :destroy

  accepts_nested_attributes_for :meal_menus, allow_destroy: true

  validates :date, presence: true
  validates :menu_image, presence: true
  validates :category, presence: true
  validates :menu_detail, presence: true

  attachment :menu_image
  enum category: { 朝食: 0, 昼食: 1, 夕食: 2, その他: 3 }

  # ユーザーがいいねしているかどうかの確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 食事内容の検索機能のためのメソッド
  def self.search_for(content)
    joins(:meal_menus).where('name LIKE ?', "%#{content}%")
  end
end

app/models/meal_menu.rb
class MealMenu < ApplicationRecord
  belongs_to :meal

  validates :name, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :comment, presence: true

  def written_by?(current_user)
    user.id == current_user.id
  end

  def nick_name
    user.nick_name
  end

  def set_meal(current_user, meal)
    self.user_id = current_user.id
    self.meal_id = meal.id
    self
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :nick_name, presence: true

  enum sex: { Female: 0, Male: 1, Others: 2, NoAnswer: 3 }
  attachment :user_image

  has_many :meals, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weights, dependent: :destroy

  def current_user?(current_user)
    id == current_user.id
  end

  # ユーザーの検索機能のためのメソッド
  def self.search_for(word)
    where('nick_name LIKE ?', "%#{word}%")
  end
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :weight, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていないと、topページだけの閲覧のみ
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nick_name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_meal

  def create
    @favorite = current_user.favorites.new(meal_id: @meal.id)
    @favorite.save
  end

  def destroy
    @favorite = current_user.favorites.find_by(meal_id: @meal.id)
    @favorite.destroy
  end

  private

  # 上記で使用する@mealの値を先に取得
  def set_meal
    @meal = Meal.find(params[:meal_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
    @meal.meal_menus.build
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = current_user.id
    if @meal.save
      redirect_to meal_path(@meal.id)
    else
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @meal = Meal.find(params[:id])
    # 他のユーザーの投稿した食事編集のページには遷移できない
    if @meal.user_id != current_user.id
      redirect_to meal_path(@meal.id)
    end
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to meal_path(@meal.id)
    else
      render :edit
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to user_path(@meal.user.id)
  end

  private

  def meal_params
    params.require(:meal).permit(:date, :menu_image, :category, :menu_detail, meal_menus_attributes: [:id, :meal_id, :name, :_destroy])
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @meal = Meal.find(params[:meal_id])
    @post_comment = PostComment.new(post_comment_params).set_meal(current_user, @meal)
    @post_comment.save
    render :create
    # redirect_to meal_path(@meal.id)　< コメント非同期通信
  end

  def destroy
    @meal = Meal.find(params[:meal_id])
    @post_comment = PostComment.find_by(id: params[:id], meal_id: params[:meal_id])
    @post_comment.destroy
    # redirect_to meal_path(params[:meal_id]) <　コメント非同期通信
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # 食事内容検索
  def search
    @content = params[:content]
    @meals = Meal.search_for(@content).page(params[:page])
  end

  # ユーザー情報検索
  def find
    @word = params[:word]
    @users = User.search_for(@word).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @meals = @user.meals.all.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    # プロフィール編集ページへ移動できるのはログインユーザーのみ
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :nick_name, :user_image, :sex, :height, :target_weight, :introduction)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def new
    @weight = Weight.new
  end

  def index
    @weights = current_user.weights.all.page(params[:page])
    # 体重のデータ取得(y軸）
    gon.weight = Weight.where(user_id: current_user.id).pluck(:weight)
    # 日付のデータ取得(x軸）
    gon.date = Weight.where(user_id: current_user.id).pluck(:date)
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user_id = current_user.id
    if @weight.save
      redirect_to weights_path
    else
      render :new
    end
  end

  def edit
    @weight = Weight.find(params[:id])
    if @weight.user_id != current_user.id
      redirect_to weights_path
    end
  end

  def update
    @weight = Weight.find(params[:id])
    if @weight.update(weight_params)
      redirect_to weights_path
    else
      render :edit
    end
  end

  private

  def weight_params
    params.require(:weight).permit(:date, :weight, :body_fat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/favorites/_favorite.html.erb
<% if meal.favorited_by?(current_user) %>
  <%= link_to meal_favorites_path(meal.id), method: :delete, remote: true do %>
    <i class="fas fa-heart like-btn" ></i>
  <% end %>
  <%= meal.favorites.count %>
<% else %>
  <%= link_to meal_favorites_path(meal.id), method: :post, remote: true do %>
    <i class="far fa-heart unlike-btn"></i>
  <% end %>
  <%= meal.favorites.count %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-<%= @meal.id %>').html("<%= j(render 'favorites/favorite', meal: @meal) %>");

app/views/favorites/destroy.js.erb
$('#favorite-<%= @meal.id %>').html("<%= j(render 'favorites/favorite', meal: @meal) %>");

app/views/meals/_meal_menu_fields.html.erb
<div class="nested-fields">
  <%= f.label :name, "Menu Name", class:"form-label" %>
  <%= f.text_field :name, class:"form-control" %>
  <%= link_to_remove_association 'ー', f %>
</div>

app/views/meals/edit.html.erb
<div class="container">

  <h2 class="mb-4">Edit Meal Record</h2>

  <!--エラーメッセージ-->
  <div class="row justify-content-center mb-3">
    <% if @meal.errors.any? %>
      <%= render 'layouts/error_messages', alert: @meal %>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="form-horizontal">
      <%= form_with model:@meal, local: true do |f| %>
        <div class="form-group">
          <%= f.label :date, "Date" %>
          <%= f.date_field :date, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.fields_for :meal_menus do |mm| %>
            <%= render 'meal_menu_fields', f: mm %>
            <%= link_to_add_association '＋', f, :meal_menus %>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.label :menu_image_id, "Meal Image" %>
          <%= f.attachment_field :menu_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :category, "Category" %>
          <%= f.select :category, options_for_select(Meal.categories.keys, @meal.category), {}, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :menu_detail, "Meal Details" %>
          <%= f.text_area :menu_detail, class:"form-control" %>
        </div>
        <%= f.submit "Update", class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/meals/new.html.erb
<div class="container">

  <h2 class="mb-4">Meal Record</h2>

  <!--エラーメッセージ-->
  <div class="row justify-content-center mb-3">
    <% if @meal.errors.any? %>
      <%= render 'layouts/error_messages', alert: @meal %>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="form-horizontal">
      <%= form_with model:@meal, local: true do |f| %>
        <div class="form-group">
          <%= f.label :date, "Date", class:"form-label" %>
          <%= f.date_field :date, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.fields_for :meal_menus do |mm| %>
            <%= render 'meal_menu_fields', f: mm %>
            <%= link_to_add_association '＋', f, :meal_menus %>
          <% end %>
        </div>
        <div class="form-group">
          <div class="custom-file">
            <%= f.label :menu_image_id, "Meal Image", class:"custome-file-label" %>
            <%= f.attachment_field :menu_image, class:"form-control-file" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :category, "Category", class:"form-label" %>
          <%= f.select :category, options_for_select(Meal.categories.keys), {}, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :menu_detail, "Menu Details", class:"form-label" %>
          <%= f.text_area :menu_detail, class:"form-control" %>
        </div>
        <div class="button">
          <%= f.submit "Save", class:"btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<!--検索フォーム-->
<%= render 'search/search' %>

<div class="container">
  <h2 class="mb-4">Meal Details</h2>

  <div class="row offset-md-2">
    <div class="md-5 text-center mb-4 mt-6">
      <%= attachment_image_tag @meal, :menu_image, :fill, 300, 300, size: "300x300", class: 'shadow mb-5 bg-white rounded', fallback: "no_image.jpg"%>
    </div>

    <div class="col-md-5 mt-3 ml-5 text-left">
      <div class="row mt-2">
        <p class="col pr-0 font-weight-bolder">Names</p>
        <h4 class="col pl-0 font-weight-bold">
          <% @meal.meal_menus.each do |mm| %>
            <%= mm.name %></br>
          <% end %>
        </h4>
      </div>

      <div class="row mt-3">
        <p class="col pr-0 font-weight-bolder">Category</p>
        <p class="col pl-0"><%= @meal.category %></p>
      </div>

      <div class="row mt-3">
        <p class="col pr-0 font-weight-bolder">Details</p>
        <p class="col pl-0"><%= @meal.menu_detail %></p>
      </div>

      <!--いいね機能の非同期通信-->
      <div class="row mt-3 ml-2">
        <div id="favorite-<%= @meal.id %>">
          <%= render 'favorites/favorite', meal: @meal %>
        </div>
      </div>

      <!--食事投稿編集ボタン、削除ボタン-->
      <div class="row mt-4">
        <% if @meal.user_id == current_user.id %>
          <p class="col"><%= link_to "Edit Meal", edit_meal_path(@meal.id), class:"btn btn-outline-primary" %></p>
          <p class="col">
            <%= link_to "Delete Meal", meal_path(@meal.id), method: :delete, class:"btn btn-outline-danger" %>
          </p>
        <% end %>
      </div>
    </div>

      <!--コメント一覧-->
      <div class="container">
        <div id="comments">
          <div class="row">
            <%= render 'post_comments/comment', meal: @meal %>
          </div>
        </div>
      </div>

      <!--コメント投稿フォーム-->
      <div class="container mt-5">
        <div class="comment-form col-sm-5 col-md-6">
          <%= form_with model:[@meal, @post_comment] do |f| %>
            <%= f.text_area :comment, rows:'5', placeholder:"Write a comment...", class:"form-control" %>
            <%= f.submit "send", class:"btn btn-outline-success mt-3" %>
          <% end %>
        </div>
      </div>

  </div>
</div>

app/views/meals/update.html.erb
<h1>Meals#update</h1>
<p>Find me in app/views/meals/update.html.erb</p>

app/views/post_comments/_comment.html.erb
<table class="table table-borderless">
  <% meal.post_comments.each do |post_comment| %>
    <tr>
      <td>
        <%= link_to user_path(post_comment.user.id) do %>
          <%= attachment_image_tag post_comment.user, :user_image, :fill, 60, 60, size: "60x60", fallback:"no_image.jpg" %>
        <% end %>
      </td>
      <td><%= post_comment.nick_name %></td>
      <td><%= post_comment.comment %></td>
      <% if post_comment.written_by?(current_user) %>
        <td>
          <%= link_to "Delete comment", meal_post_comment_path(post_comment.meal.id, post_comment.id), method: :delete, remote: true, class:"btn btn-outline-danger" %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/post_comments/create.js.erb
$("#comments").html("<%= j(render 'post_comments/comment', meal: @meal) %>");
$("#post_comment_comment").val("");

app/views/post_comments/destroy.js.erb
$("#comments").html("<%= j(render 'post_comments/comment', meal: @meal) %>");

app/views/users/edit.html.erb
<div class="container">

  <h2 class="mb-4">Edit Profile</h2>

  <!--エラーメッセージ-->
  <div class="row justify-content-center mb-3">
    <% if @user.errors.any? %>
      <%= render 'layouts/error_messages', alert: @user %>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="form-horizontal">
      <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class:"form-label" %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :nick_name, "Nick Name", class:"form-label" %>
          <%= f.text_field :nick_name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :user_image_id, "Profile Image(optional)", class:"form-label" %>
          <%= attachment_image_tag @user, :user_image, :fill, 60, 60, fallback:"no_image.jpg" %>
          <%= f.attachment_field :user_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :sex, "Sex", class:"form-label" %>
          <%= f.select :sex, options_for_select(User.sexes.keys, @user.sex), {}, class:"form-control", include_blank: "" %>
        </div>
        <div class="form-group">
          <%= f.label :height, "Height (optional)", class:"form-label" %>
          <%= f.text_field :height, placeholder: "xxx.x", class:"form-control" %> cm
        </div>
        <div class="form-group">
          <%= f.label :target_weight, "Target Weight (optional)", class:"form-label" %>
          <%= f.text_field :target_weight, placeholder: "xx.x", class:"form-control" %> kg
        </div>
        <div class="form-group">
          <%= f.label :introduction, "About Me (optional)", class:"form-label" %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <%= f.submit "Update", class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--ユーザー情報検索フォーム-->
<%= render 'search/find' %>

<!--ユーザー一覧表-->
<div class="container">
  <h2 class="mt-3 mb-4">Users</h2>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <% @users.each do |user| %>
      <div class="col pb-2">
        <div class="user shadow">
          <div class="d-flex justify-content-start align-items-center">
            <%= link_to user_path(user.id), class:"text-dark" do %>
              <%= attachment_image_tag user, :user_image, size:'50x50', fallback:"no_image.jpg" %>
              <%= user.nick_name %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!--ページネーション-->
  <div class="row my-4 page">
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mb-5">

  <!--ユーザーのプロフィール欄-->
  <div class="profile">
    <div class="profile-img"><%= attachment_image_tag @user, :user_image, :fill, 150, 130, fallback:"no_image.jpg" %></div>
    <h2 class="name"><%= @user.nick_name %></h2>
    <div class="user-status">
      <ul>
        <li>
          <div class="status-title">Sex</div>
          <div class="status-body"><%= @user.sex %></div>
        </li>
        <li>
          <div class="status-title">Height</div>
          <div class="status-body"><%= @user.height %> cm</div>
        </li>
        <li>
          <div class="status-title">Goal</div>
          <div class="status-body"><%= @user.target_weight %> kg</div>
        </li>
      </ul>
    </div>

    <div class="introduction">
      <ul>
        <li>
          <div class="intro-title">About Me</div>
          <div class="intro-body"><%= @user.introduction %></div>
        </li>
      </ul>
    </div>

    <% if @user.current_user?(current_user) %>
      <div class="edit-button">
        <%= link_to "Edit Profile", edit_user_path(@user.id), class:"btn btn-outline-secondary" %>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5">
  <!--マイページのユーザーの食事記録一覧-->
  <div class="my-meal">
    <div class="col-md-12">
      <div class="row">
        <h3 class="mr-5">My Meals</h3>
        <!--食事情報検索フォーム-->
        <%= render 'search/search' %>
      </div>

      <table class="table table-striped">
        <tr class="table-header">
          <th></th>
          <th>Date</th>
          <th>Menus</th>
          <th></th>
          <th></th>
        </tr>
        <% @meals.each do |meal| %>
          <tr class="table-body">
            <td>
              <%= link_to meal_path(meal.id) do %>
                <%= attachment_image_tag meal, :menu_image, :fill, 50, 50, fallback:"no_image.jpg" %>
              <% end %>
            </td>
            <td><%= meal.date %></td>
            <td>
              <% meal.meal_menus.each do |mm| %>
                <%= mm.name %>
              <% end %>
            </td>
            <td>Comments： <%= meal.post_comments.count %></td>
            <td id="favorite-<%= meal.id %>">
              <%= render 'favorites/favorite', meal: meal %>
            </td>
          </tr>
        <% end %>
      </table>
      <!--ページネーション-->
      <div class="row page">
        <%= paginate @meals %>
      </div>
    </div>
  </div>

</div>

app/views/weights/_form.html.erb
<!--体重投稿フォーム-->
<%= form_with model: weight, local: true do |f| %>
  <div class="form-group">
    <%= f.label :date, "Date *required", class:"form-label" %>
    <%= f.date_field :date, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :weight, "Weight *Required", class:"form-label" %>
    <%= f.text_field :weight, placeholder: "xx.x", class:"form-control" %> kg
  </div>
  <div class="form-group">
    <%= f.label :body_fat, "Body Fat", class:"form-label" %>
    <%= f.text_field :body_fat, placeholder: "xx.x", class:"form-control" %> %
  </div>
  <div class="button">
    <%= f.submit "Save", class:"btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/weights/create.html.erb
<h1>Weights#create</h1>
<p>Find me in app/views/weights/create.html.erb</p>

app/views/weights/edit.html.erb
<div class="container">
  <h2 class="mb-4">Edit Weight Record</h2>

  <!--エラーメッセージ-->
  <div class="row justify-content-center mb-3">
    <% if @weight.errors.any? %>
      <%= render 'layouts/error_messages', alert: @weight %>
    <% end %>
  </div>

  <!--体重記録変更フォーム-->
  <div class="row justify-content-center">
    <div class="form-horizontal">
      <%= render 'form', weight: @weight %>
    </div>
  </div>
  <!--weights/index.html.erbに戻る-->
  <div class="row justify-content-center mt-4">
    <%= link_to "Back", weights_path, class:"text-dark" %>
  </div>
</div>

app/views/weights/index.html.erb
<div class="container">

  <h2 class="mb-4">Weight Data</h2>

  <!--体重記録フォームへの遷移-->
  <div class="weight-form">
    <%= link_to "Record Weight", new_weight_path, class:"btn btn-warning" %>
  </div>

  <!--体重グラフ-->
  <!--体重のデータが増え、コンテイナーの幅を超えたときにスクロールができるように設定-->
  <div class="chartWrapper" style="position: relative; overflow-x: scroll;">
    <div class="chartContainer" style="height:500px;">
      <canvas id="myChart" style="position: absolute; left: 0; right: 0; top: 0; margin: auto;"></canvas>
    </div>
  </div>


  <div class="container mt-5">
    <!--体重記録一覧-->
    <div class="col-md-10 mx-auto">
      <table class="table">
        <div class="theader">
          <tr>
            <th>Date</th>
            <th>Weight(kg)</th>
            <th>Body Fat(%)</th>
            <th></th>
          </tr>
        </div>

        <div class="tbody">
          <% @weights.each do |weight| %>
            <tr>
              <th><%= weight.date %></th>
              <th><%= weight.weight %></th>
              <th>
                <% if weight.body_fat.present? %>
                  <%= weight.body_fat %>
                <% else %>
                  <p>No Record</p>
                <% end %>
              </th>
              <th><%= link_to "Edit Data", edit_weight_path(weight.id), class:"btn btn-outline-primary" %></th>
            </tr>
          <% end %>
        </div>
      </table>
      <!--ページネーション-->
      <div class="row page"><%= paginate @weights %></div>
    </div>
  </div>

</div>

app/views/weights/new.html.erb
<!--体重登録フォーム-->
<div class="container">

  <h2 class="mb-4">Weight Record</h2>

  <!--エラーメッセージ-->
  <div class="row justify-content-center mb-3">
    <% if @weight.errors.any? %>
      <%= render 'layouts/error_messages', alert: @weight %>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <div class="form-horizontal">
      <%= render 'form', weight: @weight %>
    </div>
  </div>
</div>

app/views/weights/show.html.erb
<div class="container">

  <h2 class="mb-4">Weight Data</h2>

  <!--体重記録フォームへの遷移-->
  <div class="weight-form">
    <%= link_to "Record Weight", new_weight_path, class:"btn btn-warning" %>
  </div>

  <!--体重グラフ-->
  <!--体重のデータが増え、コンテイナーの幅を超えたときにスクロールができるように設定-->
  <div class="chartWrapper" style="position: relative; overflow-x: scroll;">
    <div class="chartContainer" style="height:500px;">
      <canvas id="myChart" style="position: absolute; left: 0; right: 0; top: 0; margin: auto;"></canvas>
    </div>
  </div>


  <div class="container mt-5">
    <!--体重記録一覧-->
    <div class="col-md-10 mx-auto">
      <table class="table">
        <div class="theader">
          <tr>
            <th>Date</th>
            <th>Weight(kg)</th>
            <th>Body Fat(%)</th>
            <th></th>
          </tr>
        </div>

        <div class="tbody">
          <% @weights.each do |weight| %>
            <tr>
              <th><%= weight.date %></th>
              <th><%= weight.weight %></th>
              <th>
                <% if weight.body_fat.present? %>
                  <%= weight.body_fat %>
                <% else %>
                  <p>No Record</p>
                <% end %>
              </th>
              <th><%= link_to "Edit Data", edit_weight_path(weight.id), class:"btn btn-outline-primary" %></th>
            </tr>
          <% end %>
        </div>
      </table>
      <!--ページネーション-->
      <div class="row page"><%= paginate @weights %></div>
    </div>
  </div>

</div>