config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :meals, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :weights, only: [:new, :index, :create, :edit, :update]

  get 'search' => 'search#search'
  get 'find' => 'search#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :meal_menus, dependent: :destroy

  accepts_nested_attributes_for :meal_menus, allow_destroy: true

  validates :date, presence: true
  validates :menu_image, presence: true
  validates :category, presence: true
  validates :menu_detail, presence: true

  attachment :menu_image
  enum category: { 朝食: 0, 昼食: 1, 夕食: 2, その他: 3 }

  # ユーザーがいいねしているかどうかの確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 食事内容の検索機能のためのメソッド
  def self.search_for(content)
    joins(:meal_menus).where('name LIKE ?', "%#{content}%")
  end
end

app/models/meal_menu.rb
class MealMenu < ApplicationRecord
  belongs_to :meal

  validates :name, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :comment, presence: true

  def written_by?(current_user)
    user.id == current_user.id
  end

  def nick_name
    user.nick_name
  end

  def set_meal(current_user, meal)
    self.user_id = current_user.id
    self.meal_id = meal.id
    self
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :nick_name, presence: true

  enum sex: { Female: 0, Male: 1, Others: 2, NoAnswer: 3 }
  attachment :user_image

  has_many :meals, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weights, dependent: :destroy

  def current_user?(current_user)
    id == current_user.id
  end

  # ユーザーの検索機能のためのメソッド
  def self.search_for(word)
    where('nick_name LIKE ?', "%#{word}%")
  end
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :weight, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていないと、topページだけの閲覧のみ
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nick_name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_meal

  def create
    @favorite = current_user.favorites.new(meal_id: @meal.id)
    @favorite.save
  end

  def destroy
    @favorite = current_user.favorites.find_by(meal_id: @meal.id)
    @favorite.destroy
  end

  private

  # 上記で使用する@mealの値を先に取得
  def set_meal
    @meal = Meal.find(params[:meal_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
    @meal.meal_menus.build
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = current_user.id
    if @meal.save
      redirect_to meal_path(@meal.id)
    else
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @meal = Meal.find(params[:id])
    # 他のユーザーの投稿した食事編集のページには遷移できない
    if @meal.user_id != current_user.id
      redirect_to meal_path(@meal.id)
    end
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to meal_path(@meal.id)
    else
      render :edit
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to user_path(@meal.user.id)
  end

  private

  def meal_params
    params.require(:meal).permit(:date, :menu_image, :category, :menu_detail, meal_menus_attributes: [:id, :meal_id, :name, :_destroy])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # 食事内容検索
  def search
    @content = params[:content]
    @meals = Meal.search_for(@content).page(params[:page])
  end

  # ユーザー情報検索
  def find
    @word = params[:word]
    @users = User.search_for(@word).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @meals = @user.meals.all.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    # プロフィール編集ページへ移動できるのはログインユーザーのみ
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :nick_name, :user_image, :sex, :height, :target_weight, :introduction)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def new
    @weight = Weight.new
  end

  def index
    @weights = current_user.weights.all.page(params[:page])
    # 体重のデータ取得(y軸）
    gon.weight = Weight.where(user_id: current_user.id).pluck(:weight)
    # 日付のデータ取得(x軸）
    gon.date = Weight.where(user_id: current_user.id).pluck(:date)
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user_id = current_user.id
    if @weight.save
      redirect_to weights_path
    else
      render :new
    end
  end

  def edit
    @weight = Weight.find(params[:id])
    if @weight.user_id != current_user.id
      redirect_to weights_path
    end
  end

  def update
    @weight = Weight.find(params[:id])
    if @weight.update(weight_params)
      redirect_to weights_path
    else
      render :edit
    end
  end

  private

  def weight_params
    params.require(:weight).permit(:date, :weight, :body_fat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/homes/top.html.erb
<!--トップページ画像部分-->
<div class="py-5 text-center main-visual">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light text-dark">IT'S TIME TO MAKE YOU HEALTHY!!</h1>
      <p>
        <%= link_to "SIGN UP NOW", new_user_registration_path, class:"btn btn-warning rounded-pill text-white my-2" %>
      </p>
    </div>
  </div>
</div>

<!--サイト説明部分-->
<h1 class="content-title text-center">What you can do</h1>
<div class="container my-5">
  <div class="row">
    <div class="col-lg-6 text-center">
      <i class="fas fa-balance-scale-right scale"></i>
      <h4 class="my-3">Manage your Weight</h4>
      <p>簡単に体重の記録を行え、</br>グラフで体重の変化を確認できる</p>
    </div>
    <div class="col-lg-6 text-center">
      <i class="far fa-clipboard meal-record"></i>
      <h4 class="my-3">Manage your Meals</h4>
      <p>記録した食事内容からたくさんの人と共有</br>健康管理に対するモチベーションアップに</p>
    </div>
  </div>
</div>

app/views/search/_find.html.erb
<!--ユーザー情報検索フォーム-->
<% if user_signed_in? %>
<div class="container mt-2 mb-2">
  <div class="row justify-content-end">
    <%= form_with url: find_path, method: :get, local:true do |f| %>
      <%= f.text_field :word, placeholder: "User Name" %>
      <%= f.submit 'Search', class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/search/_search.html.erb
<!--食事内容検索フォーム-->
<% if user_signed_in? %>
<div class="container mt-2 mb-2">
  <div class="row justify-content-end">
    <%= form_with url: search_path, method: :get, local:true do |f| %>
      <%= f.text_field :content, placeholder: "Menu Name" %>
      <%= f.submit 'Search', class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/search/find.html.erb
<div class="container">
  <!--ユーザー情報検索フォーム-->
  <%= render 'find' %>

  <!--ユーザー情報検索結果-->
  <h2 class="mt-3 mb-4">Search Users for　"<%= "#{@word}" %>"</h2>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <% @users.each do |user| %>
      <div class="col pb-2">
        <div class="user shadow">
          <div class="d-flex justify-content-start align-items-center">
            <%= link_to user_path(user.id), class:"text-dark" do %>
              <%= attachment_image_tag user, :user_image, size:'50x50', fallback:"no_image.jpg" %>
              <%= user.nick_name %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!--ページネーション-->
  <div class="row page">
    <%= paginate @users %>
  </div>
</div>

app/views/search/search.html.erb
<!--食事情報検索フォーム-->
<%= render 'search' %>

<div class="container">
  <h2 class="mt-3 mb-4">Search Meals for　"<%= "#{@content}" %>"</h2>

  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>日付</th>
        <th>メニュー</th>
        <th>投稿ユーザー</th>
      </tr>
    </thead>
    <tbody>
      <% @meals.each do |meal| %>
        <tr>
          <td>
            <%= link_to meal_path(meal.id) do %>
              <%= attachment_image_tag meal, :menu_image, :fill, 50, 50, fallback:"no_image.jpg" %>
            <% end %>
          </td>
          <td>
            <%= meal.date %>
          </td>
          <td>
            <% meal.meal_menus.each do |mm| %>
              <%= mm.name %>
            <% end %>
          </td>
          <td><%= meal.user.nick_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!--ページネーション-->
  <div class="row page">
    <%= paginate @meals %>
  </div>
</div>