config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  resources :meals, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :weights, only: [:new, :index, :create, :edit, :update]

  get 'search' => 'search#search'
  get 'find' => 'search#find'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :meal_menus, dependent: :destroy

  accepts_nested_attributes_for :meal_menus, allow_destroy: true

  validates :date, presence: true
  validates :menu_image, presence: true
  validates :category, presence: true
  validates :menu_detail, presence: true

  attachment :menu_image
  enum category: { 朝食: 0, 昼食: 1, 夕食: 2, その他: 3 }

  # ユーザーがいいねしているかどうかの確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 食事内容の検索機能のためのメソッド
  def self.search_for(content)
    joins(:meal_menus).where('name LIKE ?', "%#{content}%")
  end
end

app/models/meal_menu.rb
class MealMenu < ApplicationRecord
  belongs_to :meal

  validates :name, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :comment, presence: true

  def written_by?(current_user)
    user.id == current_user.id
  end

  def nick_name
    user.nick_name
  end

  def set_meal(current_user, meal)
    self.user_id = current_user.id
    self.meal_id = meal.id
    self
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :nick_name, presence: true

  enum sex: { Female: 0, Male: 1, Others: 2, NoAnswer: 3 }
  attachment :user_image

  has_many :meals, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :weights, dependent: :destroy

  def current_user?(current_user)
    id == current_user.id
  end

  # ユーザーの検索機能のためのメソッド
  def self.search_for(word)
    where('nick_name LIKE ?', "%#{word}%")
  end
end

app/models/weight.rb
class Weight < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :weight, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
    @meal.meal_menus.build
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user_id = current_user.id
    if @meal.save
      redirect_to meal_path(@meal.id)
    else
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @meal = Meal.find(params[:id])
    # 他のユーザーの投稿した食事編集のページには遷移できない
    if @meal.user_id != current_user.id
      redirect_to meal_path(@meal.id)
    end
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to meal_path(@meal.id)
    else
      render :edit
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to user_path(@meal.user.id)
  end

  private

  def meal_params
    params.require(:meal).permit(:date, :menu_image, :category, :menu_detail, meal_menus_attributes: [:id, :meal_id, :name, :_destroy])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # 食事内容検索
  def search
    @content = params[:content]
    @meals = Meal.search_for(@content).page(params[:page])
  end

  # ユーザー情報検索
  def find
    @word = params[:word]
    @users = User.search_for(@word).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @meals = @user.meals.all.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
    # プロフィール編集ページへ移動できるのはログインユーザーのみ
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :nick_name, :user_image, :sex, :height, :target_weight, :introduction)
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def new
    @weight = Weight.new
  end

  def index
    @weights = current_user.weights.all.page(params[:page])
    # 体重のデータ取得(y軸）
    gon.weight = Weight.where(user_id: current_user.id).pluck(:weight)
    # 日付のデータ取得(x軸）
    gon.date = Weight.where(user_id: current_user.id).pluck(:date)
  end

  def create
    @weight = Weight.new(weight_params)
    @weight.user_id = current_user.id
    if @weight.save
      redirect_to weights_path
    else
      render :new
    end
  end

  def edit
    @weight = Weight.find(params[:id])
    if @weight.user_id != current_user.id
      redirect_to weights_path
    end
  end

  def update
    @weight = Weight.find(params[:id])
    if @weight.update(weight_params)
      redirect_to weights_path
    else
      render :edit
    end
  end

  private

  def weight_params
    params.require(:weight).permit(:date, :weight, :body_fat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/layouts/_error_messages.html.erb
<div class="alert-message">
  You got <%= alert.errors.count %> errors:</br>
  <% alert.errors.full_messages.each do |message| %>
    <%= message %></br>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<div class="container pt-4 my-md-5 pt-md-5 border-top">
  <div class="row ml-4">
    <div class="col-12 col-md">
      <h5 class="mb-2">My Ideal Body</h5>
      <small class="d-block mb-3 text-muted">© 2021.Y.K</small>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="d-flex flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

  <!--ユーザーがログインしているかどうかで、ロゴの遷移先を変更-->
  <% if user_signed_in? %>
    <h5 class="my-0 mr-md-auto font-weight-bold">
      <%= link_to "My Ideal Body", user_path(current_user.id), method: :get, class:"text-dark text-decoration-none" %>
    </h5>
  <% else %>
    <h5 class="my-0 mr-md-auto font-weight-bold">
      <%= link_to "My Ideal Body", root_path, class:"text-dark text-decoration-none" %>
    </h5>
  <% end %>

  <!--メニュー表示をユーザーがログインしているかどうかで変更-->
  <nav class="my-2 my-md-0 mr-md-3">
    <% if user_signed_in? %>
      <%= link_to weights_path, class:"p-2 text-dark" do %>
        <i class="fas fa-weight"> Weight</i>
      <% end %>
      <%= link_to new_meal_path, class:"p-2 text-dark" do %>
        <i class="fas fa-utensils"> Meal</i>
      <% end %>
      <%= link_to users_path, class:"p-2 text-dark" do %>
        <i class="fas fa-users"> Users</i>
      <% end %>
      <%= link_to user_path(current_user.id), method: :get, class:"p-2 text-dark" do %>
        <i class="fas fa-user-cog"> MyPage</i>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class:"text-dark" do %>
        <i class="fas fa-sign-out-alt"> Logout</i>
      <% end %>
    <% else %>
      <%= link_to new_user_registration_path, class:"p-2 text-dark" do %>
        <i class="fas fa-user-plus"> SignUp</i>
      <% end %>
      <%= link_to new_user_session_path, class:"text-dark" do %>
        <i class="fas fa-sign-in-alt"> Login</i>
      <% end %>
    <% end %>
  </nav>

</div>

app/views/layouts/_search.html.erb
<!--検索フォーム-->
<% if user_signed_in? %>
<div class="container mt-2 mb-2">
  <div class="row justify-content-center">
    <%= form_with url: search_path, method: :get, local:true do |f| %>
      <%= f.text_field :content %>
      <%= f.submit '検索', class:"btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyIdealBody</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--railsのデータをJSに渡す-->
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>